### PR TITLE
ItemKey: Distinguish between Bpm and IntegerBpm

### LINKED ISSUE #334: Add another `ItemKey` variant for float BPM values
Right now, MP4 has its integer and float BPM atoms map to the integer BPM atom:

https://github.com/Serial-ATA/lofty-rs/blob/f4be1e3775e233847f1620fb4295302817f95341/src/tag/item.rs#L280

These are different values, and should not collide with each other. There should be an `IntegerBpm` and (`FloatBpm` | `PreciseBpm`) `ItemKey` variant.

I do not know yet if other tag formats have a specified float BPM item.

### PR DESCRIPTION
**Pull request by uklotzde**
Fixes #334.

### CODE REVIEW

**Comment by Serial-ATA** [comment]
I believe "BPM" in Vorbis Comments and APE is also expected to be an integer value. At least that's how Picard uses it.

**Comment by uklotzde** [comment]
> I believe "BPM" in Vorbis Comments and APE is also expected to be an integer value. At least that's how Picard uses it.

I am only aware of ID3v2 and MP4 which impose these restriction. MP4 by atom type and ID3v2 by [standard definition](https://github.com/id3/ID3v2.4/blob/516075e38ff648a6390e48aff490abed987d3199/id3v2.4.0-frames.txt#L376).

**Comment by uklotzde** [comment]
Client still need to handle case that the integer field contains an arbitrary string, e.g. a decimal number.

**Comment by Serial-ATA** [comment]
Yeah, better to play it safe here.

This is marked draft, was there anything else planned for it?

**Comment by uklotzde** [comment]
> Yeah, better to play it safe here.
> 
> This is marked draft, was there anything else planned for it?

I first wanted to publish this for discussion. If you agree we could merge it.

**Comment by Serial-ATA** [comment]
Yep, these changes are good. Thanks!

**Pull request merged**
