### PR TITLE
ID3v2: Add simplified getters and setters for TXXX frames

### PR DESCRIPTION
**Pull request by Serial-ATA**
This adds `Id3v2Tag::{get, insert}_user_text` to simplify the process of working with TXXX frames with their descriptions.

### CODE REVIEW

**Comment by Serial-ATA** [comment]
@uklotzde Just making you aware of this, since you could probably use it.

**Comment by uklotzde** [comment]
Yeah. You can easily get it wrong as we have seen ;) Working with the low-level ID3v2 frames is error prone due to the twofold addressing scheme.

**Review by uklotzde — APPROVED** [review]

**Comment by Serial-ATA** [comment]
Realized I added a getter and setter with no way to remove them :smile:. All good now.

**Comment by uklotzde** [comment]
@Serial-ATA It is time for a 0.14.1 release to unlock all the fixes and extensions for dependent projects.

**Pull request merged**
